### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by brandonjoyce** [sonerdy/double#35]
I could use some help with this one.  If a code of conduct will help welcome in new contributors, let's get it done.

**Comment by jvantuyl** [comment]
Maybe just adopt [the Contributor Covenant](https://www.contributor-covenant.org/)?  There's some controversy around it, though I've never found it to be much more than mental gymnastics to justify "people who make supposedly invaluable contributions should / have earned the right to behave badly".  And, really, if that's the stance, there's not much point in a Code of Conduct at all.

**Comment by brandonjoyce** [comment]
Will reopen if needed, but I haven't heard much about this recently.
